[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.11.1"

[[constraint]]
  name = "github.com/aerospike/aerospike-client-go"
  version = "v1.34.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.1"

[[override]]
  branch = "release-8.0"
  name = "github.com/appscode/kutil"

[prune]
  go-tests = true
  unused-packages = true
