[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.10.4"

[[constraint]]
  name = "github.com/aerospike/aerospike-client-go"
  version = "v1.33.0"

[prune]
  go-tests = true
  unused-packages = true
