[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.11.3"

[[constraint]]
  name = "github.com/aerospike/aerospike-client-go"
  version = "v1.35.2"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.3"

[[override]]
  branch = "release-8.0"
  name = "github.com/appscode/kutil"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"

[prune]
  go-tests = true
  unused-packages = true
