apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: eu.gcr.io/<project-id>/aerospike-operator-e2e
    docker:
      dockerfilePath: Dockerfile.skaffold.e2e
    workspace: .
deploy:
  kubectl:
    manifests:
      - hack/skaffold.e2e.yaml
profiles:
- name: gke
  build:
    googleCloudBuild:
      projectId: <project-id>
- name: minikube
  build:
    local: {}
