apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: eu.gcr.io/<project-id>/aerospike-operator
    docker:
      dockerfilePath: Dockerfile.skaffold.operator
    workspace: .
deploy:
  kubectl:
    manifests:
      - docs/examples/00-prereqs.yml
      - hack/skaffold.operator.yaml
profiles:
- name: gke
  build:
    googleCloudBuild:
      projectId: <project-id>
- name: minikube
  build:
    local: {}
