apiVersion: v1
kind: Namespace
metadata:
  name: aerospike-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aerospike-operator
  namespace: aerospike-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aerospike-operator
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - delete
  - create
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - watch
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - create
  - update
  - list
  - watch
- apiGroups: [""]
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - list
  - watch
- apiGroups: [""]
  resources:
  - endpoints
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - delete
  - create
  - list
  - watch
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
- apiGroups: [""]
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - aerospike.travelaudience.com
  resources:
  - aerospikeclusters
  - aerospikenamespacebackups
  - aerospikenamespacerestores
  verbs:
  - list
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aerospike-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aerospike-operator
subjects:
- kind: ServiceAccount
  name: aerospike-operator
  namespace: aerospike-operator
