apiVersion: v1
kind: Service
metadata:
  labels:
    app: aerospike-operator
  name: aerospike-operator
  namespace: aerospike-operator
spec:
  selector:
    app: aerospike-operator
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aerospike-operator
  name: aerospike-operator
  namespace: aerospike-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerospike-operator
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: aerospike-operator
    spec:
      containers:
      - name: aerospike-operator
        image: quay.io/travelaudience/aerospike-operator:0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
        args:
        - /usr/local/bin/aerospike-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccountName: aerospike-operator
