apiVersion: v1
kind: Service
metadata:
  labels:
    app: aerospike-operator
  name: aerospike-operator
  namespace: aerospike-operator
spec:
  selector:
    app: aerospike-operator
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aerospike-operator
  name: aerospike-operator
  namespace: aerospike-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aerospike-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: aerospike-operator
    spec:
      containers:
      - name: aerospike-operator
        image: quay.io/travelaudience/aerospike-operator:0.6.0-dev
        imagePullPolicy: Always
        args:
        - /usr/local/bin/aerospike-operator
        ports:
        - containerPort: 8443
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 1
      serviceAccountName: aerospike-operator
