apiVersion: v1
kind: Namespace
metadata:
  name: aerospike-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aerospike-operator
  namespace: aerospike-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aerospike-operator
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - watch
- apiGroups: [""]
  resources:
  - configmaps
  - pods
  - services
  verbs:
  - create
  - list
  - watch
- apiGroups: [""]
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - aerospike.com
  resources:
  - aerospikeclusters
  verbs:
  - list
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aerospike-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aerospike-operator
subjects:
- kind: ServiceAccount
  name: aerospike-operator
  namespace: aerospike-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aerospike-operator
  name: aerospike-operator
  namespace: aerospike-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerospike-operator
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: aerospike-operator
    spec:
      containers:
      - name: aerospike-operator
        image: quay.io/travelaudience/aerospike-operator:latest
        imagePullPolicy: Always
        args:
        - /usr/local/bin/aerospike-operator
      serviceAccountName: aerospike-operator
