apiVersion: v1
kind: Service
metadata:
  labels:
    app: aerospike-operator
  name: aerospike-operator
  namespace: aerospike-operator
spec:
  selector:
    app: aerospike-operator
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: aerospike-operator
  name: aerospike-operator
  namespace: aerospike-operator
spec:
  containers:
  - name: aerospike-operator
    image: gcr.io/__PROJECT_ID__/aerospike-operator
    imagePullPolicy: IfNotPresent
    args:
    - /aerospike-operator
    - --debug
    ports:
    - containerPort: 8443
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      requests:
        memory: 64Mi
        cpu: 100m
      limits:
        memory: 64Mi
        cpu: 100m
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8443
        scheme: HTTPS
      initialDelaySeconds: 3
      periodSeconds: 2
      failureThreshold: 1
  serviceAccountName: aerospike-operator
